<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ram" ignored="0" name="Default test" tests="6" failures="1" timestamp="28 Nov 2022 07:54:16 GMT" time="63.797" errors="0">
  <testcase name="user__createnewaccount" time="10.402" classname="com.test.Authenticate"/>
  <testcase name="user_enters__empty_password_and_Username" time="6.393" classname="com.test.Authenticate"/>
  <testcase name="user_enters__forgotpassword_invalid_email" time="10.939" classname="com.test.Authenticate"/>
  <testcase name="user_enters__forgotpassword_invalid_phone" time="13.629" classname="com.test.Authenticate">
    <failure type="org.openqa.selenium.NoSuchWindowException" message="no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=107.0.1418.56)
Build info: version: &amp;apos;4.5.3&amp;apos;, revision: &amp;apos;4b786a1e430&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_333&amp;apos;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [11d6a28b350a84d8f9a14b5c4125d93d, findElements {using=name, value=email}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 107.0.1418.56, ms:edgeOptions: {debuggerAddress: localhost:50335}, msedge: {msedgedriverVersion: 107.0.1418.56 (5b47a5c50066..., userDataDir: C:\Users\Ram\AppData\Local\...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50335/devtoo..., se:cdpVersion: 107.0.1418.56, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 11d6a28b350a84d8f9a14b5c4125d93d">
      <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=107.0.1418.56)
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_333'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [11d6a28b350a84d8f9a14b5c4125d93d, findElements {using=name, value=email}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 107.0.1418.56, ms:edgeOptions: {debuggerAddress: localhost:50335}, msedge: {msedgedriverVersion: 107.0.1418.56 (5b47a5c50066..., userDataDir: C:\Users\Ram\AppData\Local\...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50335/devtoo..., se:cdpVersion: 107.0.1418.56, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 11d6a28b350a84d8f9a14b5c4125d93d
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:179)
at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:108)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:380)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:372)
at org.openqa.selenium.support.pagefactory.ByAll.findElement(ByAll.java:53)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:136)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:365)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:357)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at com.sun.proxy.$Proxy13.sendKeys(Unknown Source)
at com.Help.BaseClass.passValues(BaseClass.java:102)
at com.test.Authenticate.user_enters__forgotpassword_invalid_phone(Authenticate.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- user_enters__forgotpassword_invalid_phone -->
  <testcase name="user_enters__invalid_password_invalid_Username_throwerror" time="15.663" classname="com.test.Authenticate"/>
  <testcase name="when_invalid_password_valid_Username_throwerror" time="6.698" classname="com.test.Authenticate"/>
</testsuite> <!-- Default test -->
